[package]
name = "mapf"
version = "0.1.0"
edition = "2021"
description = "Base traits and utilities for multi-agent planning"
license = "Apache-2.0"
repository = "https://github.com/open-rmf/mapf"
keywords = ["mapf", "multi", "agent", "planning", "search"]

[badges]
maintenance = {status = "experimental"}

[dependencies]
# nalgebra = "0.30"
nalgebra = { path = "../../nalgebra" }
time-point = "0.1"
sorted-vec = { git = "https://gitlab.com/grey12/sorted-vec", branch = "master" }
simba = "*"
num-complex = "*"
cached = "0.34"
approx = "*"
num = "*"
